language: go

go:
  - 1.6

# magic word to use faster/newer container-based architecture
sudo: false

before_install:
  - go get -u github.com/golang/lint/golint

script:
  - make
  - $(GOPATH)/bin/dg-scraper
  - $(GOPATH)/bin/dg-build

notifications:
  email:
    on_success: never

# Removed for now because Travis _still_ doesn't support Postgres 9.5 and we're
# using upsert. Hopefully one day we can go back.
#
#addons:
#  postgresql: "9.5"
#
#before_script:
#  - psql -U postgres -c 'CREATE DATABASE "deathguild-test";'

env:
  global:

    # $DATABASE_URL
    - secure: "I29o6f6LYqCPRZ7rDsQEu3qmO4xOCTnLKSqDkYUmcP/KEwUufnzK9rf1+3u/oAaOod7rR2vWukrblsHdeZ69dbxabJQv91TU3OYWSjsB2X4Z5uhP8vxw2fqNawZIlh8jRdyqrEY/ovseZjTUTETNHl4XhgPhiujFWk16wLWoHklJ8A0OvrgXrqobd59v2vH3IaXgHbsNJgF88tBR6nr4gZAd60UdpjLPfT+uY7w6h18M8Dgvgy3iFhlqZAvH2JFeb/stjlXTsgujKwK2Rq2/Gv0OmNrsq3VT/sVbEjaKuetK4xkR1W6CfmZgkP1CljcwMRJDKzKEYwMaWZlR49cXXISme7sp0VMqgDWgWNfJCgNybplV051TNwgx0+kB+v2JvGIlGllUs0jsHnG/9TrZ8L/23IzmwgTUF2see0fUQf0+AEapN3VOckj10+IQDWEDkd31NhIG1/0hFat3b3c4N/tsrOfiodFU4KnW3buUDwzYESE3PDjgCA84s7IOlfFaPupedGmIFNsKGIq3ZftZ4H/Y8JVj8sBfuX92G+ZBy5RiaQF/RCnppmUmFXLx/As83f4yV/byWxyCQbUd2GgxukWOLCs3I5BzytLV0bTlg2PzqyB96g+PAJbAGnIN6Ho5d0CzXZ+lEzeK7XNWkNO+bFg9xgjph/r+Brp/GyY75tg="

    # $TEST_DATABASE_URL
    - secure: "KcKK8xugyTfHpOgRb+DCysnqsA97uSoEKjx+ExnUQ6CAXFYdR9W3zNRGG4Hyg3orziZpCI5DtN/IM3+inzTSvyAAU9WC7kYJJryO8gB6Yg/h0qbVlutVo9daGsvALymfJQRw2XlgeBIWJExvmI0du9f0WlP1mD+wiK5cgkfO3LJd7wjFPbFvp90Z6c4FyaS0N7lHqv8aPuDz6J5Zo2QUvDDhLJH0mPMynt7TJdAnv1idDdm2ORYLXFr0UQCA1ORP/7RNDMv9U+nkZuHus0g2oSPTzCTVTZkCimKW4fbLl6o+swj5ESpVRD0bkIg8veOnaVQxKMjacdRcpE5hrglzYfOmcKhNp9bmwxk1ClS/N/ZgZ5V3XPhVB8YUz9E6I0R4kOc7JXlVhBoyAAsAKHIvQihO8aA/WFFElwqIKJZE9lco6XgTyS2WN0TA2y20A4256S+okZJHsNEon9D8KF/mEvVfedY3KJf8p7802904vF0n5RcvfrnB5abbsm7yZDwM8ZBidAuPP3XI9TZVOP8rRD9J4Cx8ftKycgA+uarxlfVG01ZYCxi2c0FitQBhcIS4N1KvM7VZKKIArKd5LJIkOGidI2I4dsBJMNTg4WY3gIQBAX1sWiqVJ5apwE3nh9DzltX8ML0ea+B8mb0LpH35ER59QFs792wmLqPaksNOaSo="
