language: go

go:
  - 1.6

# magic word to use faster/newer container-based architecture
sudo: false

before_install:
  - go get -u github.com/golang/lint/golint

script:
  - DATABASE_URL=$TEST_DATABASE_URL make

notifications:
  email:
    on_success: never

# Removed for now because Travis _still_ doesn't support Postgres 9.5 and we're
# using upsert. Hopefully one day we can go back.
#
#addons:
#  postgresql: "9.5"
#
#before_script:
#  - psql -U postgres -c 'CREATE DATABASE "deathguild-test";'

env:
  global:

    # $PRODUCTION_DATABASE_URL
    - secure: "oC4bjzfkcIjP/1RT92XS8nz0GwLYk1ryn1FY4FWy4qcZDdpM66vFb4WULyv94iTb3BvzdjNAmYKqSCA6pEpgzjM90cillvqhHWqkXu6BhnmQ2GcO9HUJOs0f8NkLyORZ60AfENaVvvjRvDx45PPUnBBrloSHM7Daqo2J+JHqEuESesPhfDKb3sFS19fD+8emTtGrnNqZlGfqJ29vg7sk0u5FQIFD85+J1QHoFkgo651uzicnChPW9HrLkb3dTnf6yf2bbZRbD1cbKSgtTe80PI+CDDLc7Dn/4GR+vg5TOtp7cf0p2J1ycwCyg4ZZc2++88zMzeEd8EpxyEeQP7fBNIIHLNF4rmrNsXQ0o8dIFByabbpniK2q5xN49bbvF+/V3n/e6iG2XtyfYoVvc8PPwUFbgwBCUGl+YrDRmoRhbGl4aBFl2yHVA8g5gGFNNVXe85TAealWqLWZnjWrdHmwEnaeERBHVRJD8M4ohoc2vf6dQ6elZ/ITlLY3D/jNKOzp+UZReQ7/SkUvUK/1PnGQHNlpQRpNZmzpM/Tm1hI38b1W6hn42L5ihvpE+tu4BM191Lr6+kEaMLp0mQYArF5kVY2C8/8A+H5K7YzXPVSphv+ePXvjdE7Oeypm8RkHmSuzXY7O7NoROExoOLXolNVZnkHtgw+7oZmDytXqWw61fEA="

    # $TEST_DATABASE_URL
    - secure: "KcKK8xugyTfHpOgRb+DCysnqsA97uSoEKjx+ExnUQ6CAXFYdR9W3zNRGG4Hyg3orziZpCI5DtN/IM3+inzTSvyAAU9WC7kYJJryO8gB6Yg/h0qbVlutVo9daGsvALymfJQRw2XlgeBIWJExvmI0du9f0WlP1mD+wiK5cgkfO3LJd7wjFPbFvp90Z6c4FyaS0N7lHqv8aPuDz6J5Zo2QUvDDhLJH0mPMynt7TJdAnv1idDdm2ORYLXFr0UQCA1ORP/7RNDMv9U+nkZuHus0g2oSPTzCTVTZkCimKW4fbLl6o+swj5ESpVRD0bkIg8veOnaVQxKMjacdRcpE5hrglzYfOmcKhNp9bmwxk1ClS/N/ZgZ5V3XPhVB8YUz9E6I0R4kOc7JXlVhBoyAAsAKHIvQihO8aA/WFFElwqIKJZE9lco6XgTyS2WN0TA2y20A4256S+okZJHsNEon9D8KF/mEvVfedY3KJf8p7802904vF0n5RcvfrnB5abbsm7yZDwM8ZBidAuPP3XI9TZVOP8rRD9J4Cx8ftKycgA+uarxlfVG01ZYCxi2c0FitQBhcIS4N1KvM7VZKKIArKd5LJIkOGidI2I4dsBJMNTg4WY3gIQBAX1sWiqVJ5apwE3nh9DzltX8ML0ea+B8mb0LpH35ER59QFs792wmLqPaksNOaSo="
