language: go

go:
  - 1.6

# magic word to use faster/newer container-based architecture
sudo: false

before_install:
  - go get -u github.com/golang/lint/golint

script:
  - make
  - $GOPATH/bin/dg-scraper
  - $GOPATH/bin/dg-build
  - $GOPATH/bin/dg-enrich-songs

notifications:
  email:
    on_success: never

# Removed for now because Travis _still_ doesn't support Postgres 9.5 and we're
# using upsert. Hopefully one day we can go back.
#
#addons:
#  postgresql: "9.5"
#
#before_script:
#  - psql -U postgres -c 'CREATE DATABASE "deathguild-test";'

env:
  global:

    # $CLIENT_ID
    - secure: "BSxGvCbpr9mP6u5ePE3K9T+HakDBpTkJ/GNRDfvEn2Oe5wZ1xO1RjWdP2LNBDGIQOIBBWugfbJP+xdTc2yNGLVJ7Po2iAI35BMZxH+kdIpoF9+63+B7lZTbT9ii2bXWBgjaqMKbHnaWLiLOsGZL/l3N07ytcetZsLwiqInYBrHomIM+BIME9m6cAE2Eo01/cSAANeEEvqpc4PRsBLyXZe0QJJBJyjiOy856jcNnTnUyqoNl+UQVnYYGMvcmFTOZJTPqOVo4e1UIuOsSj5IV1c+KTfL3pLjMXvajUHtc/gJ40YeSwW+w4u2PZSV41ANveSNPpA+cxFLfTCDi7J5oTBmqm4IzbGtEtYP2wM1ZYzbh76m+7ke+47kmlS6hORtdatJR8h7nRA7MEZ7OiBhA1nFw/oQjMQs+k93UEFx/PxBH2bG8BPNkc9aFtbahYMqex2AGufSzAJkT9ElCGAvMVLM+DIDD8781hwCUGoHxZJBhvdWonx2+tWyE4H+AfLgmh1p4ppOZ5Rk718q/6BEqwec2s+OcgxagkBnwdj/OiNpu2Y5kSr7dCaKI/ty9kxMhPMy/m+8mpp3688+WJH97SpNQ/Rkun1Wc67Gj7hkffHItmrqpbAolqWqXbF2TZQYHki2S2oni5BsSrubKLF/sr4ObSA4S3F95FfbCEN1/J31o="

    # $CLIENT_SECRET
    - secure: "BSxGvCbpr9mP6u5ePE3K9T+HakDBpTkJ/GNRDfvEn2Oe5wZ1xO1RjWdP2LNBDGIQOIBBWugfbJP+xdTc2yNGLVJ7Po2iAI35BMZxH+kdIpoF9+63+B7lZTbT9ii2bXWBgjaqMKbHnaWLiLOsGZL/l3N07ytcetZsLwiqInYBrHomIM+BIME9m6cAE2Eo01/cSAANeEEvqpc4PRsBLyXZe0QJJBJyjiOy856jcNnTnUyqoNl+UQVnYYGMvcmFTOZJTPqOVo4e1UIuOsSj5IV1c+KTfL3pLjMXvajUHtc/gJ40YeSwW+w4u2PZSV41ANveSNPpA+cxFLfTCDi7J5oTBmqm4IzbGtEtYP2wM1ZYzbh76m+7ke+47kmlS6hORtdatJR8h7nRA7MEZ7OiBhA1nFw/oQjMQs+k93UEFx/PxBH2bG8BPNkc9aFtbahYMqex2AGufSzAJkT9ElCGAvMVLM+DIDD8781hwCUGoHxZJBhvdWonx2+tWyE4H+AfLgmh1p4ppOZ5Rk718q/6BEqwec2s+OcgxagkBnwdj/OiNpu2Y5kSr7dCaKI/ty9kxMhPMy/m+8mpp3688+WJH97SpNQ/Rkun1Wc67Gj7hkffHItmrqpbAolqWqXbF2TZQYHki2S2oni5BsSrubKLF/sr4ObSA4S3F95FfbCEN1/J31o="

    # $DATABASE_URL
    - secure: "I29o6f6LYqCPRZ7rDsQEu3qmO4xOCTnLKSqDkYUmcP/KEwUufnzK9rf1+3u/oAaOod7rR2vWukrblsHdeZ69dbxabJQv91TU3OYWSjsB2X4Z5uhP8vxw2fqNawZIlh8jRdyqrEY/ovseZjTUTETNHl4XhgPhiujFWk16wLWoHklJ8A0OvrgXrqobd59v2vH3IaXgHbsNJgF88tBR6nr4gZAd60UdpjLPfT+uY7w6h18M8Dgvgy3iFhlqZAvH2JFeb/stjlXTsgujKwK2Rq2/Gv0OmNrsq3VT/sVbEjaKuetK4xkR1W6CfmZgkP1CljcwMRJDKzKEYwMaWZlR49cXXISme7sp0VMqgDWgWNfJCgNybplV051TNwgx0+kB+v2JvGIlGllUs0jsHnG/9TrZ8L/23IzmwgTUF2see0fUQf0+AEapN3VOckj10+IQDWEDkd31NhIG1/0hFat3b3c4N/tsrOfiodFU4KnW3buUDwzYESE3PDjgCA84s7IOlfFaPupedGmIFNsKGIq3ZftZ4H/Y8JVj8sBfuX92G+ZBy5RiaQF/RCnppmUmFXLx/As83f4yV/byWxyCQbUd2GgxukWOLCs3I5BzytLV0bTlg2PzqyB96g+PAJbAGnIN6Ho5d0CzXZ+lEzeK7XNWkNO+bFg9xgjph/r+Brp/GyY75tg="

    # $REFRESH_TOKEN
    - secure: "sjg4v85fo63uQhW07GLcEOY0cR5wiicXsuhg80q6hno5gElRo3CztOpjMY5d4+Q4W5AB8ciQkXCkJUwj2KPvgppXXAyR4+CHXQhUau7Prht+qEF2UJ3LGb8LVtUFKYH8j1AjEikW2AgFtatQLcsB1N46NKwDJNqQ+E7eH+z73ixOc52F7wRaVDfYCcu1gmq4bicovir4S+dpioyV0tKXWNnY4KbTGr9CGnq5MzAIrWa3MY418fERzqyrGpT1PEiL4Yun4iqPuzUW54HQAmWGsDBkfyL9rQD3EIs8E0qvw6MAcWGt8YDWsUWh1QT8xWFRPsPnLd4FnoFmg6oEDIrnI/wKyyv3GJULLev0p403P6JIXZhu9Gc+9nPRvejcwrvP6/7GSUhJWe47ovidtx3hmqzttanmtXVH/HXTeyF6Ci5+gzrPUo8SmK3YjIM5S7vnTUnbsHk7yDuQP2EOR0CcEHpgD3yuAN8ugUt+O53RpUWoQrRXl/GuKYqvVAM3eoXNOPgthiU3valaP5lAGymii9ATN7tetMKiqM4zQAGcdO6OGyi2iVnw0i7mNI37O7crhExKrNq5rS3KMkyaGJBiBU/RArEwl+zAK2z0Tn8ERV619LM33Vh159Nh/xdYW0AxI+94G3qGzbgkrpOZfmanKpplBDXdG+00Yabqf6bf0Zg="

    # $TEST_DATABASE_URL
    - secure: "KcKK8xugyTfHpOgRb+DCysnqsA97uSoEKjx+ExnUQ6CAXFYdR9W3zNRGG4Hyg3orziZpCI5DtN/IM3+inzTSvyAAU9WC7kYJJryO8gB6Yg/h0qbVlutVo9daGsvALymfJQRw2XlgeBIWJExvmI0du9f0WlP1mD+wiK5cgkfO3LJd7wjFPbFvp90Z6c4FyaS0N7lHqv8aPuDz6J5Zo2QUvDDhLJH0mPMynt7TJdAnv1idDdm2ORYLXFr0UQCA1ORP/7RNDMv9U+nkZuHus0g2oSPTzCTVTZkCimKW4fbLl6o+swj5ESpVRD0bkIg8veOnaVQxKMjacdRcpE5hrglzYfOmcKhNp9bmwxk1ClS/N/ZgZ5V3XPhVB8YUz9E6I0R4kOc7JXlVhBoyAAsAKHIvQihO8aA/WFFElwqIKJZE9lco6XgTyS2WN0TA2y20A4256S+okZJHsNEon9D8KF/mEvVfedY3KJf8p7802904vF0n5RcvfrnB5abbsm7yZDwM8ZBidAuPP3XI9TZVOP8rRD9J4Cx8ftKycgA+uarxlfVG01ZYCxi2c0FitQBhcIS4N1KvM7VZKKIArKd5LJIkOGidI2I4dsBJMNTg4WY3gIQBAX1sWiqVJ5apwE3nh9DzltX8ML0ea+B8mb0LpH35ER59QFs792wmLqPaksNOaSo="
